services:

  database:
    image: "postgres:16"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  redis:
    image: "redis:7"
    networks:
      - omero

  omeroserver:
    image: "openmicroscopy/omero-server:5"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"
    ulimits:
      nofile:
        soft: 8192
        hard: 65536

  fill-omero-server:
    build:
      context: .
      dockerfile: Dockerfile.fill_omero
    depends_on:
      - database
      - omeroserver
    environment:
      OMERO_HOST: omeroserver
      OMERO_PORT: "4064"
      OMERO_USER: root
      OMERO_PASSWORD: omero
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    volumes:
      - "omero:/OMERO"

  omeroweb:
    build:
      context: .
      dockerfile: Dockerfile.omeroweb
    networks:
      - omero
    depends_on:
      - omeroserver
    ports:
      - "4080:4080"
    volumes:
      - "omero:/OMERO"
      - "config_volume:/opt/omero/web/OMERO.web/etc/grid"
      - "log_volume:/tmp/jipipe_logs"
  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    networks:
      - omero
    depends_on:
      - redis
      - omeroweb
    restart: on-failure
    volumes:
      - "omero:/OMERO"  # If needed for data access
      - "config_volume:/opt/omero/web/OMERO.web/etc/grid"
      - "log_volume:/tmp/jipipe_logs"
    environment:
      OMERODIR: /opt/omero/web/OMERO.web
networks:
  omero:

volumes:
  database:
  omero:
  config_volume:
  log_volume:
