FROM openmicroscopy/omero-web-standalone:5

USER root

# Install JIPipeRunner
WORKDIR /opt
RUN git clone https://asb-git.hki-jena.de/MWank/OMERO_JIPipe_Plugin.git
WORKDIR /opt/OMERO_JIPipe_Plugin
RUN git reset --hard cd7e5303
RUN /opt/omero/web/venv3/bin/pip install /opt/OMERO_JIPipe_Plugin

# ---- INSTALL PLUGIN DEPENDENCIES ----
COPY requirements.txt /tmp/requirements.txt
RUN /opt/omero/web/venv3/bin/pip install -r /tmp/requirements.txt && rm /tmp/requirements.txt

# ---- REGISTER OMERO.web PLUGIN and start Omeroweb via entrypoint----
COPY omeroweb_entrypoint.sh /opt/omeroweb_entrypoint.sh
RUN chmod +x /opt/omeroweb_entrypoint.sh
ENTRYPOINT ["/opt/omeroweb_entrypoint.sh"]
