services:

  podman-socket:
    build:
      context: .
      dockerfile: Dockerfile.podman
    privileged: true
    # Useful if Docker daemon has userns-remap enabled; otherwise optional:
    userns_mode: "host"
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined   # mainly relevant on AppArmor hosts
      - label=disable         # mainly relevant on SELinux hosts
    command: ["/entrypoint.sh"]
    environment:
      ENABLE_NVIDIA_GPU: "0"
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "podman_socket:/podman-sock"
      - "podman_storage:/var/lib/containers"
      - "j2o-files:/j2o-host/j2o-files"
      - "j2o-artifacts:/j2o-host/j2o-artifacts/artifacts"
    networks:
      - omero

  database:
    image: "postgres:16"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  redis:
    image: "redis:7"
    networks:
      - omero

  omeroserver:
    image: "openmicroscopy/omero-server:5"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
      CONFIG_omero_policy_binary__access: +read,+write,+image,+plate
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"
    ulimits:
      nofile:
        soft: 8192
        hard: 65536

  fill-omero-server:
    build:
      context: .
      dockerfile: Dockerfile.fill_omero
    depends_on:
      - database
      - omeroserver
    environment:
      OMERO_HOST: omeroserver
      OMERO_PORT: "4064"
      OMERO_USER: root
      OMERO_PASSWORD: omero
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    volumes:
      - "omero:/OMERO"

  omeroweb:
    build:
      context: .
      dockerfile: Dockerfile.omeroweb
    networks:
      - omero
    depends_on:
      - omeroserver
    ports:
      - "4080:4080"
    environment:
      CONTAINER_HOST: "unix:///podman-sock/podman.sock"
      J2O_HOST_DATA_PATH: "/j2o-host/j2o-files/data"
      J2O_HOST_ARTIFACTS_PATH: "/j2o-host/j2o-artifacts"
      ENABLE_NVIDIA_GPU: "0"
    volumes:
      - "omero:/OMERO"
      - "config_volume:/opt/omero/web/OMERO.web/etc/grid"
      - "j2o-files:/opt/omero/web/OMERO.web/var/j2o-files"
      - "j2o-artifacts:/root/.local/share/JIPipe/artifacts"
      - "podman_socket:/podman-sock"
  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    networks:
      - omero
    depends_on:
      - redis
      - omeroweb
    restart: on-failure
    volumes:
      - "omero:/OMERO"  # If needed for data access
      - "config_volume:/opt/omero/web/OMERO.web/etc/grid"
      - "j2o-files:/opt/omero/web/OMERO.web/var/j2o-files"
      - "j2o-artifacts:/root/.local/share/JIPipe/artifacts"
      - "podman_socket:/podman-sock"
    environment:
      OMERODIR: /opt/omero/web/OMERO.web
      CONTAINER_HOST: "unix:///podman-sock/podman.sock"
      J2O_HOST_DATA_PATH: "/j2o-host/j2o-files/data"
      J2O_HOST_ARTIFACTS_PATH: "/j2o-host/j2o-artifacts"
networks:
  omero:
volumes:
  j2o-files:
  j2o-artifacts:
  database:
  omero:
  config_volume:
  podman_socket:
  podman_storage:
